### ISSUE TITLE
Example Scroll not work

### ISSUE THREAD

**Issue by ddiegommachado** [lipten/vue-slidePage#1]
I have a list in v-for:
```<ul class="nav">
          <li  v-for="image in images" :key="image" class="col-sm-4 wrapper-actuation step animated zoomIn">
            <figure>
              <img class="img-fluid" :src="image.img" :alt="image.alt">
            </figure>
            <h4 class="text-center red w-1">{{ image.text }}</h4>
          </li>
        </ul>
```
But example Scroll not work....my images are cliped on responsive mode!

Heeelp!

**Comment by lipten** [comment]
remove class 'step' is work.
```
          <li  v-for="image in images" :key="image" class="col-sm-4 wrapper-actuation animated zoomIn">
            <figure>
              <img class="img-fluid" :src="image.img" :alt="image.alt">
            </figure>
            <h4 class="text-center red w-1">{{ image.text }}</h4>
          </li>
```
I will fix this bug later

**Comment by lipten** [comment]
@ddiegommachado I am fixed ，please run `npm install vue-slidepage`

**Comment by ddiegommachado** [comment]
@lipten 
I already run npm install...
My problem is not in plugin operation. Only in the "Scroll" example, as I have a list, does not show all elements.

**Comment by ddiegommachado** [comment]
@lipten Another problem (maybe), is when to build. My index.html is blank, 
does not render. I'm not sure, but it could be because of the slide-page-vue + AOS plugin

**Comment by lipten** [comment]
@ddiegommachado  Is the ”Scroll“ example you're referring to in the [slidePage](https://github.com/lipten/slidePage/blob/master/examples/scroll.html)?

**Comment by ddiegommachado** [comment]
@lipten Yeees!! exactly...look my: https://beta.site.mambowifi.com in the fourth section on responsive mode  (Chrome) "Setores de Atuação". The list is cliped....the circles.

**Comment by lipten** [comment]
If I understand you correctly, annotation the circles width, the circle will not be clip from the list
```
#actuation .wrapper-actuation figure[data-v-47963396] {
    border-radius: 50%;
    /* width: 250px; */
    overflow: hidden;
    margin: 5px auto;
}
```

**Comment by ddiegommachado** [comment]
No bro!! Same problem... on responsive mode, don't showed complete list.....I've tried no width.

**Comment by lipten** [comment]
Please run `npm info slidePage` to make sure the `version: '3.1.71',`

 if not `3.1.71`, please run `npm install slidePage ` to update it

**Comment by ddiegommachado** [comment]
Yes, my version is 3.1.71. Not working!!! Shiit!

**Comment by lipten** [comment]
Can you update your website(https://beta.site.mambowifi.com) ? 
I don't think the latest version is used

**Comment by ddiegommachado** [comment]
Yes man! I ran npm info slidePage and show me 3.1.71. Yesterday, ran git push to the (https://beta.site.mambowifi.com) with updates

**Comment by lipten** [comment]
Hey Bro , Your website is not running the latest version.
I wrote an example for you to look at (http://lipten.link/projects/slidePage3/examples/scroll2.html)

**Comment by ddiegommachado** [comment]
Ran npm info SlidePage and show:
`{ name: 'slidePage',
  description: 'slidePage.js is a simple and universal to use libary to create fullscreen scrolling websites',
  'dist-tags': { latest: '3.1.71' }, 
 version: '3.1.71',`
This is ok? Whats wrong?

**Comment by lipten** [comment]
The version is right! but your site  looks like still old.
How did you usage vue-slidepage？

**Comment by ddiegommachado** [comment]
I'm importing:
`import { SlideContainer, SlidePage } from 'vue-slidepage'`

**Comment by ddiegommachado** [comment]
I believe with everything alright. Localhost and online are with the same version. I can not find anything wrong

**Comment by lipten** [comment]
Okay, Can you give me a social account to chat with you?  
You can send it to my email(lipten@foxmail.com)
We need to talk!

**Comment by ddiegommachado** [comment]
Do you have hangout? ddiego.mmachado@gmail.com
